# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ZanderShah/halite-3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ZanderShah/halite-3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ZanderShah/halite-3/CMakeFiles /Users/ZanderShah/halite-3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ZanderShah/halite-3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyBot

# Build rule for target.
MyBot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyBot
.PHONY : MyBot

# fast build rule for target.
MyBot/fast:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/build
.PHONY : MyBot/fast

MyBot.o: MyBot.cpp.o

.PHONY : MyBot.o

# target to build an object file
MyBot.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/MyBot.cpp.o
.PHONY : MyBot.cpp.o

MyBot.i: MyBot.cpp.i

.PHONY : MyBot.i

# target to preprocess a source file
MyBot.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/MyBot.cpp.i
.PHONY : MyBot.cpp.i

MyBot.s: MyBot.cpp.s

.PHONY : MyBot.s

# target to generate assembly for a file
MyBot.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/MyBot.cpp.s
.PHONY : MyBot.cpp.s

hlt/command.o: hlt/command.cpp.o

.PHONY : hlt/command.o

# target to build an object file
hlt/command.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/command.cpp.o
.PHONY : hlt/command.cpp.o

hlt/command.i: hlt/command.cpp.i

.PHONY : hlt/command.i

# target to preprocess a source file
hlt/command.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/command.cpp.i
.PHONY : hlt/command.cpp.i

hlt/command.s: hlt/command.cpp.s

.PHONY : hlt/command.s

# target to generate assembly for a file
hlt/command.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/command.cpp.s
.PHONY : hlt/command.cpp.s

hlt/constants.o: hlt/constants.cpp.o

.PHONY : hlt/constants.o

# target to build an object file
hlt/constants.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/constants.cpp.o
.PHONY : hlt/constants.cpp.o

hlt/constants.i: hlt/constants.cpp.i

.PHONY : hlt/constants.i

# target to preprocess a source file
hlt/constants.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/constants.cpp.i
.PHONY : hlt/constants.cpp.i

hlt/constants.s: hlt/constants.cpp.s

.PHONY : hlt/constants.s

# target to generate assembly for a file
hlt/constants.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/constants.cpp.s
.PHONY : hlt/constants.cpp.s

hlt/dropoff.o: hlt/dropoff.cpp.o

.PHONY : hlt/dropoff.o

# target to build an object file
hlt/dropoff.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/dropoff.cpp.o
.PHONY : hlt/dropoff.cpp.o

hlt/dropoff.i: hlt/dropoff.cpp.i

.PHONY : hlt/dropoff.i

# target to preprocess a source file
hlt/dropoff.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/dropoff.cpp.i
.PHONY : hlt/dropoff.cpp.i

hlt/dropoff.s: hlt/dropoff.cpp.s

.PHONY : hlt/dropoff.s

# target to generate assembly for a file
hlt/dropoff.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/dropoff.cpp.s
.PHONY : hlt/dropoff.cpp.s

hlt/game.o: hlt/game.cpp.o

.PHONY : hlt/game.o

# target to build an object file
hlt/game.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/game.cpp.o
.PHONY : hlt/game.cpp.o

hlt/game.i: hlt/game.cpp.i

.PHONY : hlt/game.i

# target to preprocess a source file
hlt/game.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/game.cpp.i
.PHONY : hlt/game.cpp.i

hlt/game.s: hlt/game.cpp.s

.PHONY : hlt/game.s

# target to generate assembly for a file
hlt/game.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/game.cpp.s
.PHONY : hlt/game.cpp.s

hlt/game_map.o: hlt/game_map.cpp.o

.PHONY : hlt/game_map.o

# target to build an object file
hlt/game_map.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/game_map.cpp.o
.PHONY : hlt/game_map.cpp.o

hlt/game_map.i: hlt/game_map.cpp.i

.PHONY : hlt/game_map.i

# target to preprocess a source file
hlt/game_map.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/game_map.cpp.i
.PHONY : hlt/game_map.cpp.i

hlt/game_map.s: hlt/game_map.cpp.s

.PHONY : hlt/game_map.s

# target to generate assembly for a file
hlt/game_map.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/game_map.cpp.s
.PHONY : hlt/game_map.cpp.s

hlt/log.o: hlt/log.cpp.o

.PHONY : hlt/log.o

# target to build an object file
hlt/log.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/log.cpp.o
.PHONY : hlt/log.cpp.o

hlt/log.i: hlt/log.cpp.i

.PHONY : hlt/log.i

# target to preprocess a source file
hlt/log.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/log.cpp.i
.PHONY : hlt/log.cpp.i

hlt/log.s: hlt/log.cpp.s

.PHONY : hlt/log.s

# target to generate assembly for a file
hlt/log.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/log.cpp.s
.PHONY : hlt/log.cpp.s

hlt/player.o: hlt/player.cpp.o

.PHONY : hlt/player.o

# target to build an object file
hlt/player.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/player.cpp.o
.PHONY : hlt/player.cpp.o

hlt/player.i: hlt/player.cpp.i

.PHONY : hlt/player.i

# target to preprocess a source file
hlt/player.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/player.cpp.i
.PHONY : hlt/player.cpp.i

hlt/player.s: hlt/player.cpp.s

.PHONY : hlt/player.s

# target to generate assembly for a file
hlt/player.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/player.cpp.s
.PHONY : hlt/player.cpp.s

hlt/ship.o: hlt/ship.cpp.o

.PHONY : hlt/ship.o

# target to build an object file
hlt/ship.cpp.o:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/ship.cpp.o
.PHONY : hlt/ship.cpp.o

hlt/ship.i: hlt/ship.cpp.i

.PHONY : hlt/ship.i

# target to preprocess a source file
hlt/ship.cpp.i:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/ship.cpp.i
.PHONY : hlt/ship.cpp.i

hlt/ship.s: hlt/ship.cpp.s

.PHONY : hlt/ship.s

# target to generate assembly for a file
hlt/ship.cpp.s:
	$(MAKE) -f CMakeFiles/MyBot.dir/build.make CMakeFiles/MyBot.dir/hlt/ship.cpp.s
.PHONY : hlt/ship.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MyBot"
	@echo "... MyBot.o"
	@echo "... MyBot.i"
	@echo "... MyBot.s"
	@echo "... hlt/command.o"
	@echo "... hlt/command.i"
	@echo "... hlt/command.s"
	@echo "... hlt/constants.o"
	@echo "... hlt/constants.i"
	@echo "... hlt/constants.s"
	@echo "... hlt/dropoff.o"
	@echo "... hlt/dropoff.i"
	@echo "... hlt/dropoff.s"
	@echo "... hlt/game.o"
	@echo "... hlt/game.i"
	@echo "... hlt/game.s"
	@echo "... hlt/game_map.o"
	@echo "... hlt/game_map.i"
	@echo "... hlt/game_map.s"
	@echo "... hlt/log.o"
	@echo "... hlt/log.i"
	@echo "... hlt/log.s"
	@echo "... hlt/player.o"
	@echo "... hlt/player.i"
	@echo "... hlt/player.s"
	@echo "... hlt/ship.o"
	@echo "... hlt/ship.i"
	@echo "... hlt/ship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

